### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by VMohinder** [aguarda/ADLPCC#1]
I was trying to install the dependencies with conda and: 

PackagesNotFoundError: The following packages are not available from current channels:

  - ipython-genutils==0.2.0
  - scipy==1.5.4
  - tensorflow-compression==1.3
  - jupyter-client==6.1.12
  - jupyter-core==4.7.1
  - jupyterlab-pygments==0.1.2
  - opt-einsum==3.3.0
  - prometheus-client==0.10.1
  - jupyterlab-widgets==1.0.0
  - async-generator==1.10

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

Which channels contain these versions of the required packages? Newer versions can be used?

**Comment by VMohinder** [comment]
For instance, in conda-forge channel the version of scipy jumps from 1.5.3 to 1.6.0.

conda search --channel conda-forge scipy

.
.
.
scipy                          1.5.3  py37h8911b10_0  conda-forge         
scipy                          1.5.3  py38h828c644_0  conda-forge         
scipy                          1.5.3  py38hb2138dd_0  conda-forge         
scipy                          1.5.3  py39hee8e79c_0  conda-forge         
scipy                          1.5.3  py39hf3f25e7_0  conda-forge         
scipy                          1.6.0  py37h14a347d_0  conda-forge         
scipy                          1.6.0  py37h91f5cce_0  pkgs/main           
scipy                          1.6.0  py37ha768fb6_0  conda-forge         
scipy                          1.6.0  py37hf56f3a7_0  pkgs/main
.
.
.

**Comment by aguarda** [comment]
Hi!
I have updated the `requirements.txt` file, and removed some unnecessary dependencies.

If the specific version is not available through `conda`, you may install via `pip` instead. However, the version does not need to be the same, but should be compatible (as displayed by the operator `~=` in the updated file).

As for TensorFlow and the `tensorflow-compression` module, both must be installed via `pip` as `pip install tensorflow-gpu==1.15 tensorflow-compression==1.3`. Please refer to the project GitHub page https://github.com/tensorflow/compression/tree/v1.3 for more detailed information, if needed.

**Comment by VMohinder** [comment]
> Hi!
> I have updated the `requirements.txt` file, and removed some unnecessary dependencies.
> 
> If the specific version is not available through `conda`, you may install via `pip` instead. However, the version does not need to be the same, but should be compatible (as displayed by the operator `~=` in the updated file).
> 
> As for TensorFlow and the `tensorflow-compression` module, both must be installed via `pip` as `pip install tensorflow-gpu==1.15 tensorflow-compression==1.3`. Please refer to the project GitHub page https://github.com/tensorflow/compression/tree/v1.3 for more detailed information, if needed.

**Comment by VMohinder** [comment]
Hi, AGuarda, thanks for the instructions.
I'll try again.

**Comment by VMohinder** [comment]
Installation seems to work now. I was able to compress and decompress.
Thanks again.
